# Build PumpSaver with a persistent build directory.
#
#   .\build.ps1              compile
#   .\build.ps1 -Upload      compile then flash COM5
#   .\build.ps1 -Port COM7 -Upload
#   .\build.ps1 -Clean       throw away the cache and rebuild from scratch
#
# WHY THE BUILD PATH MATTERS: arduino-cli does not keep its temporary build
# directory between runs, so every plain `arduino-cli compile` recompiles the
# whole ESP32 core (119 files) and ESPAsyncWebServer + AsyncTCP (111 files) --
# about 20 MB of object files and ~97 seconds. Those never change. Pointing at
# a stable directory drops a rebuild to ~11 s, because only the 15 sketch files
# are recompiled.
#
# The Arduino IDE keeps its own persistent build folder, so the same applies
# there: the FIRST compile of a sketch is slow, the rest are not. Changing any
# board menu option (PSRAM, flash size, USB CDC) changes the FQBN and forces a
# full rebuild.

param([switch]$Upload, [switch]$Clean, [switch]$Sim, [string]$Port = "COM5")

# Arduino IDE 2.x installs either per-user (LOCALAPPDATA\Programs) or
# system-wide (Program Files), depending on which installer was used -- and
# both exist across our machines.  Probe rather than hardcode: pinning either
# one breaks the build on every machine that has the other.
$cliCandidates = @(
  "$env:LOCALAPPDATA\Programs\arduino-ide\resources\app\lib\backend\resources\arduino-cli.exe",
  "$env:ProgramFiles\Arduino IDE\resources\app\lib\backend\resources\arduino-cli.exe",
  "${env:ProgramFiles(x86)}\Arduino IDE\resources\app\lib\backend\resources\arduino-cli.exe"
)
$cli = $cliCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $cli) {
  $onPath = Get-Command arduino-cli.exe -ErrorAction SilentlyContinue
  if ($onPath) { $cli = $onPath.Source }
}
if (-not $cli) {
  Write-Error "arduino-cli not found. Looked in:`n  $($cliCandidates -join "`n  ")`nand on PATH."
  exit 1
}
$cfg = "$env:USERPROFILE\.arduinoIDE\arduino-cli.yaml"
$fqbn = "esp32:esp32:esp32s3:CDCOnBoot=cdc,FlashSize=16M,PSRAM=opi,PartitionScheme=app3M_fat9M_16MB"
$sketch = $PSScriptRoot
$bp = "$env:LOCALAPPDATA\Temp\pumpsaver-build"

# -Sim builds the simulated-plant firmware from the SAME source and the same
# commit as the real one.  Separate build paths on purpose: the two differ by a
# -D, so sharing a cache would force a full rebuild on every switch between
# them, and it is also far too easy to flash the one you did not mean to.
# sim_flag.h is GENERATED here on every run and gitignored, so it can never
# disagree with the binary just produced, and both firmwares come from one
# commit.  Separate build paths per mode: they differ by a define, so one
# shared cache would force a full rebuild on every switch, and it is far too
# easy to flash the one you did not mean to.
#
# Passing -DSIM=1 through --build-property compiler.cpp.extra_flags was tried
# and does not work -- it perturbs arduino-cli's core cache key such that the
# Arduino core loses symbols, and AsyncTCP then fails to link with
# "undefined reference to micros".
if ($Sim) { $bp = "$bp-sim" }
$simVal = 0
if ($Sim) { $simVal = 1 }
@(
  "// GENERATED by build.ps1 -- do not edit, do not commit.",
  "// SIM 1 = simulated plant.  SIM 0 = real drives over Modbus RTU.",
  "#pragma once",
  "#define SIM $simVal"
) | Set-Content -Path (Join-Path $PSScriptRoot "sim_flag.h") -Encoding utf8

if ($Clean -and (Test-Path $bp)) { Remove-Item -LiteralPath $bp -Recurse -Force; "cleaned $bp" }

$sw = [Diagnostics.Stopwatch]::StartNew()
# Not $args -- that is a PowerShell automatic variable.
& $cli --config-file $cfg compile --fqbn $fqbn $sketch --build-path $bp --warnings default
# $LASTEXITCODE, never $?.  In Windows PowerShell 5.1 a native command that
# writes ANYTHING to stderr -- a compiler warning is enough -- sets $? to false
# even when it exited 0, so $? reported a clean build as a failure.
if ($LASTEXITCODE -ne 0) { Write-Error "compile failed"; exit 1 }
"built in $([math]::Round($sw.Elapsed.TotalSeconds,1)) s  $(if ($Sim) { "[SIM plant]" } else { "[real drives]" })"

if ($Upload) {
    "uploading to $Port ..."
    & $cli --config-file $cfg upload -p $Port --fqbn $fqbn --input-dir "$bp" $sketch
    if ($LASTEXITCODE -eq 0) { "flashed" } else { Write-Error "upload failed - for the first flash hold BOOT, tap RESET, release BOOT" }
}
